UI order table model
JohnnyLAmpAz/smartmag pull request #12
Opened 2024-03-03 11:09 UTC by DavideBrambilla98

- Aggiunta la classe relativa al modello della tabella per gli ordini
- Aggiunta la classe relativa al modello della tabella per i prodotti di un ordine

2024-03-04 23:16 UTC, JohnnyLAmpAz requested changes
Vedi commenti. In particolare trovo proprio sbagliato il _ProductOrderTableModel_ perché vai ad usare i Record. Ti committo a breve la mia versione.

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +			bm = new BoxModel(b);
`getBoxModel` non restituisce mai null: se non esiste lo crea lui
```suggestion
		BoxModel bm = getBoxModel(b);
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +	public BoxModel CreateBox(Box b)
```suggestion
	public static BoxModel createBox(Box b)
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +	public void create() throws SQLIntegrityConstraintViolationException {
privato poiché esiste già createBox publico per creare un Box
```suggestion
	private void create() throws SQLIntegrityConstraintViolationException {
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +			notifyChangeListeners(null);
Non rimuoverei l'istanza dalla mappa, semplicemente si elimina record (dal db e dell'istanza) e si notifica; isSavedInDb ritornerà _false_
```suggestion
			record = null;
			notifyChangeListeners(null);
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	}
Non si dovrebbero restituire publicamente i record del DB. Se l'intento era quello di fornire la lista di prodotti e quantità dell'ordine, ricordiamoci che questo è presente come mappa dentro l'oggetto Ordine ottenibile con *getOrdine().getProdotti()*. Se era per uso interno, c'è direttamente _listaProdottiOrdiniRecord_. Quindi si potrebbe farne a meno.
```suggestion
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +			notifyChangeListeners(null); // evento per notificare il cambiamento
già chiamato da _createProdottoOrdineRecord_
```suggestion
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +		notifyChangeListeners(null); // evento per notificare il cambiamento
giò chiamato da _updateOrdine_
```suggestion
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public void deleteRecords() throws ParseException {
Più chiaro
```suggestion
	public void deleteOrdine() throws ParseException {
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +			instances.remove(getOrderModelOf(ordine));
di nuovo, ci limitiamo ad eliminare record e notificare; l'istanza del modello rimane
```suggestion
			orderRecord = null;
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public static TreeMap<Integer, OrderModel> treeMapFilter(
```suggestion
	private static TreeMap<Integer, OrderModel> treeMapFilter(
```

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ProductModel.java
Non faccio review in quanto poi si mergia la versione aggiornata da altro branch

2024-03-04 23:16 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductOrderTableModel.java
Sei andato a gestire la cosa con i Record... Abbiamo a disposizione i modelli, nello specifico quello dell'ordine che ci restituisce l'oggetto Ordine al cui interno troviamo la mappa della "lista della spesa" che associa prodotti alle quantità. Sto per committare la mia versione

2024-03-04 23:25 UTC, JohnnyLAmpAz commented
Ho committato [(ae7c7f4)](https://github.com/JohnnyLAmpAz/smartmag/pull/12/commits/ae7c7f4a94523ff823da225bc2d80e187e852013) la mia versione di _ProductOrderTableModel_. Contiene anche una finestra di prova con tabella prodotti relativa ad ordine di id `0` (creane uno nel tuo db locale). Nota come utilizzo solo il modello...

2024-03-05 11:47 UTC, JohnnyLAmpAz approved these changes

2024-03-05 21:12 UTC, MassimilianoGervasoni approved these changes

2024-03-06 12:43 UTC, merged