creazione ProdTableModel + aggiornamento ProductModel + piccole modifiche generali
JohnnyLAmpAz/smartmag pull request #14
Opened 2024-03-03 14:33 UTC by MassimilianoGervasoni

- creata classe relativa al modello della tabella per i prodotti
- modifiche generali necessarie per implementare la nuova classe
- aggiornamento classe ProductModel
- aggiunte notify

2024-03-03 15:06 UTC, JohnnyLAmpAz approved these changes

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +	public BoxModel CreateBox(Box b)
Meglio statico
```suggestion
	public static BoxModel createBox(Box b)
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +			bm = new BoxModel(b);
Il metodo _getBoxModel_ crea già lui un nuovo modello se non esiste e non restituisce mai _null_. Vedi:
https://github.com/JohnnyLAmpAz/smartmag/blob/2de9116f93d98a7393a6accf0f1950258b04d3cf/proj_eclipse/src/main/java/smartmag/models/BoxModel.java#L193-L216

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +				;
```suggestion
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/BoxModel.java
> +	public static TreeMap<String, BoxModel> treeMapFilter(
```suggestion
	private static TreeMap<String, BoxModel> treeMapFilter(
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ProductModel.java
> +			this.prodotto = p;
Clone per evitare modifiche inattese
```suggestion
			this.prodotto = p.clone();
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ProductModel.java
> +	public ProdottoRecord getRecord() {
```suggestion
	protected ProdottoRecord getRecord() {
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ProductModel.java
> +	public static TreeMap<Integer, ProductModel> treeMapFilter(
```suggestion
	private static TreeMap<Integer, ProductModel> treeMapFilter(
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductTableModel.java
> +		// TODO Auto-generated method stub
```suggestion
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductTableModel.java
> +		// TODO Auto-generated method stub
```suggestion
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductTableModel.java
> +		// TODO Auto-generated method stub
```suggestion
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductTableModel.java
> +		Prodotto p = getProductModelat(rowIndex).getProdotto();
```suggestion
		Prodotto p = getProductModelAt(rowIndex).getProdotto();
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductTableModel.java
> +	public ProductModel getProductModelat(int rowIndex) {
```suggestion
	public ProductModel getProductModelAt(int rowIndex) {
```

2024-03-03 15:06 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/ui/ProductTableModel.java
> +		// TODO Auto-generated method stub
```suggestion
```

2024-03-03 15:08 UTC, JohnnyLAmpAz requested changes
A parte i commenti e le modifiche proposte, tutto buono 👍

2024-03-04 16:01 UTC, DavideBrambilla98 approved these changes

2024-03-04 17:17 UTC, JohnnyLAmpAz approved these changes

2024-03-04 18:05 UTC, merged