Order model
JohnnyLAmpAz/smartmag pull request #9
Opened 2024-02-29 10:10 UTC by DavideBrambilla98

Ho aggiunto la classe per il model dell'ordine che permette di:
- Creare nuovi ordini
- Modificare ordini già esistenti
- Eliminare ordini

Questo modello gestisce sia i record dell'ordine sia i record di prodottiOrdini del DB.

2024-02-29 20:12 UTC, JohnnyLAmpAz requested changes
Guarda i commenti che ho messo. Per il resto, LGTM 💪.

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/data/Ordine.java
> +	public void inserisciProdotto(Prodotto o, int q) throws IOException {
Questo metodo lo implementerei nel _modello_ e non nella classe Prodotto, perché è lui che si interfaccia al DB

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public void createOrdineRecord()
lo metterei private perché gestisce i record

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public void createProdottoOrdineRecord() {
anche questo private
```suggestion
	private void createProdottoOrdineRecord() {
```

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public void updateQtaProdottoOrdine(Ordine o, Prodotto p, int qta)
essendo d'istanza l'ordine non server passarlo come parametro

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public void deleteProdottoOrdine(Ordine o, Prodotto p)
anche qua

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +			this.ordine.setDataCompletamento(o.getDataCompletamento());
Manca di recuperare anche i suoi prodotti con le qta e impostarle con ordine.setProdotti() con la hashmap!

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public boolean productOrderIsSavedInDb(int idO, int idP) {
same

2024-02-29 20:12 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Anche qui bisogna tenere conto che non inserisce nell'oggetto ordine la hashmap prodotti-qta! Vista l'utilità del metodo si può pensare di tenerlo così o (meglio) di rinominarlo _ordineFromOrdineRecord_ e di chiarire nel javadoc

2024-03-01 14:57 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public void deleteProdottoOrdine(Ordine o, Prodotto p)
Modificato lasciando solo prodotto da passare al metodo poichè serve a scegliere dal DB il record corretto da eliminare.

2024-03-01 15:10 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public boolean productOrderIsSavedInDb(int idO, int idP) {
non ho capito che modifica devo fare.
Intendi che dovrei controllare che nel DB sia stata inserita anche la quantità per dire se esiste o no il record?

2024-03-01 15:21 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Il problema è che ordine record non gestisce i prodotti, infatti anche quando viene creato un nuovo record di un ordine, non viene passata la HashMap dei prodotti.

Ecco il costruttore di un record dell'ordine:

    public OrdineRecord(Integer id, String tipo, String stato, String dataem, String dataco) {
        super(Ordine.ORDINE);

        setId(id);
        setTipo(tipo);
        setStato(stato);
        setDataem(dataem);
        setDataco(dataco);
        resetChangedOnNotNull();
    }

Per gestire i prodotti e le relative quantità si utilizzano i ProdottiordiniRecord.

2024-03-01 15:33 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public boolean productOrderIsSavedInDb(int idO, int idP) {
No, semplicemente come sopra è inutile dover passare anche idOrdine perché hai già a disposizione l'attributo d'istanza dell'ordine gestito dall'istanza del modello. Non `idO` ma `this.ordine.getId()`.

2024-03-01 15:35 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/data/Ordine.java
> +	public void inserisciProdotto(Prodotto o, int q) throws IOException {
Ho cancellato il metodo dalla classe ordine e l'ho implementato nella classe OrderModel:

	public void inserisciProdotto(Prodotto p, int q)
			throws SQLIntegrityConstraintViolationException {

		getListaProdottiFromDb(this.ordine.getId());

		if (p.isValid() && q > 0)
			createProdottoOrdineRecord();
		else
			throw new SQLIntegrityConstraintViolationException(
					"Ordine #" + p.getId() + " prodotto non valido o qta < 0");
	}

2024-03-01 15:45 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/data/Ordine.java
> +	public void inserisciProdotto(Prodotto o, int q) throws IOException {
Rimosso il metodo dalla classe Ordine e implementato nella classe OrderModel:

	public void inserisciProdotto(Prodotto p, int q)
			throws SQLIntegrityConstraintViolationException {

		getListaProdottiFromDb(this.ordine.getId());

		if (p.isValid() && q > 0) {
			createProdottoOrdineRecord(p, q);
		} else
			throw new SQLIntegrityConstraintViolationException(
					"Ordine #" + p.getId() + " prodotto non valido o qta < 0");
	}

2024-03-01 15:47 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +	public boolean productOrderIsSavedInDb(int idO, int idP) {
Ah ok, sistemato

2024-03-01 15:48 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Vero ma si possono settare con

https://github.com/JohnnyLAmpAz/smartmag/blob/dd8c1d03d2ed4d0b87ed770663810826caebe5f8/proj_eclipse/src/main/java/smartmag/data/Ordine.java#L80-L82

2024-03-01 15:52 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Ma questo metodo non aggiorna gli oggetti della classe ordine, aggiorna i record di ordine.
Dato che nei record di ordine non sono presenti i prodotti non capisco come potrei aggiornarli.

2024-03-01 15:56 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Se intendi aggiornare gli oggetti della classe ordine partendo da un record invece, dovrei fare un nuovo metodo getOrderFromDb o qualcosa di simile.
Ma questo metodo deve accedere sia a OrderRecord che a ProductOrderRecord per avere tutti gli attributi necessari per aggiornare l'oggetto ordine.

2024-03-01 15:58 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Nono, è dell'istanza Ordine! ordine.setProdotti()

2024-03-01 16:01 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Ma aggiorna i prodotti dell'istanza dell'ordine il metodo setProdotti()
Non lo posso usare per aggiornare il record di un ordine

2024-03-01 16:34 UTC, JohnnyLAmpAz commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
> Restituisce un ordine partendo dal suo record

Scritto così pensavo dovesse restituire l'intero oggetto Ordine (**prodotti compresi**) dai suoi record nelle due tabelle. Se invece intendi ritornare un oggetto ordine senza lista prodotti allora va bene così

2024-03-01 16:41 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
ah ma pensavo ti riferissi alla classe copyOrdineIntoRecord, invece intendi ordineFromOrdineRecord

2024-03-01 16:43 UTC, DavideBrambilla98 commented on proj_eclipse/src/main/java/smartmag/models/OrderModel.java
> +				.parse(r.getDataco());
Si si hai ragione, meglio recuperare anche i prodotti dell'ordine.
Per farlo al posto che usare OrdineRecord, uso ProdottiordiniRecord e dovrei riuscire.

2024-03-02 13:39 UTC, JohnnyLAmpAz approved these changes
Goooood 👍

2024-03-02 13:40 UTC, merged